# Generated by Django 5.0.3 on 2024-03-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_postid_alter_post_downvotes_alter_post_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
