# Generated by Django 5.0.3 on 2024-03-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_tagged_alter_post_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
