# Generated by Django 5.0.3 on 2024-03-10 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhaar',
        ),
        migrations.AddField(
            model_name='user',
            name='followering',
            field=models.ManyToManyField(related_name='the_people_i_am_currently_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='users_who_are_following_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
