# Generated by Django 5.0.3 on 2024-03-10 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_aadhaar_user_followering_user_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followering',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
